Repository MinecraftForge/Documentation, pull requests merged in 2018-03, with the labels that each got.

#147 Adds Config.md
  docs/config/@config.md
  mkdocs.yml
Labels: New Page

#145 Add section on checking update result from code
  docs/gettingstarted/autoupdate.md
Labels: Page Improvement

#128 #94: interaction documentation for onBlockDestroyedByPlayer
  docs/blocks/interaction.md
Labels: Page Improvement, Waiting for Changes

#61 Add Models category
  docs/blocks/blocks.md
  docs/blocks/states.md
  docs/blockstates/forgeBlockstates.md
  docs/blockstates/introduction.md
  docs/items/items.md
  docs/models/advanced/extended-blockstates.md
  docs/models/advanced/ibakedmodel.md
  docs/models/advanced/icustommodelloader.md
  docs/models/advanced/imodel.md
  docs/models/advanced/imodelstate+part.md
  docs/models/advanced/introduction.md
  docs/models/advanced/itemoverridelist.md
  docs/models/advanced/perspective.md
  docs/models/blockstates/example.png
  docs/models/blockstates/forgeBlockstates.md
  docs/models/blockstates/introduction.md
  docs/models/color.md
  docs/models/files.md
  docs/models/introduction.md
  docs/models/overrides.md
  docs/models/using.md
  mkdocs.yml
Labels: New Page, Waiting for Changes

#150 Add section about persisting Chunk and TileEntity capabilities
  docs/datastorage/capabilities.md
Labels: Page Improvement, Waiting for Changes

#154 Replace non-breaking spaces screwing up formatting
  docs/gettingstarted/index.md
Labels: Minor Text Fixes
