Repository MinecraftForge/Documentation, pull requests merged in 2019-02, with the labels that each got.

#205 Clean up the docs for SimpleImpl
  docs/networking/simpleimpl.md
Labels: Out of Date Information

#201 Basic entity sync documentation
  docs/networking/entities.md
  mkdocs.yml
Labels: New Page

#213 Convert oredict page to tags
  docs/utilities/oredictionary.md
  docs/utilities/tags.md
  mkdocs.yml
Labels: 1.13, New Page, Waiting for Changes
