Repository MinecraftForge/Documentation, pull requests merged in 2020-07, with the labels that each got.

#314 fix typo
  docs/models/color.md
Labels: 1.14, Minor Text Fixes

#301 Update index.md
  docs/gettingstarted/index.md
Labels: 1.14, Minor Text Fixes

#295 Removed deprecated link
  mkdocs.yml
Labels: 1.15, Out of Date Information

#288 Rewrite the docs for Block States
  docs/blocks/states.md
  mkdocs.yml
Labels: 1.14, Out of Date Information, Waiting for Changes

#291 Particle Overview
  docs/effects/particles.md
  mkdocs.yml
Labels: 1.14, New Page, Waiting for Changes

#311 Data generators documentation
  docs/datagen/intro.md
  docs/datagen/modelproviders.md
  mkdocs.yml
Labels: New Page, Waiting for Changes

#297 [1.14.x] Rewrite docs for Registries
  docs/blocks/blocks.md
  docs/concepts/registries.md
  docs/effects/sounds.md
  docs/items/items.md
Labels: 1.14, Out of Date Information, Page Improvement, Waiting for Changes
