Repository MinecraftForge/Documentation, pull requests merged in 2020-04, with the labels that each got.

#250 Fix TileEntity references for 1.13+
  docs/tileentities/tileentity.md
Labels: 1.14, Out of Date Information

#265 Update edit marker in index.md
  docs/gettingstarted/index.md
Labels: 1.14, Minor Text Fixes

#273 typo correction examplemode => examplemod
  docs/concepts/internationalization.md
Labels: 1.14, Minor Text Fixes

#247 Getting Started: Add info about generating Run/Launch Configs
  docs/gettingstarted/index.md
Labels: 1.14, Needs Rebase, Out of Date Information

#248 Fix Forge Update Checker references for 1.13+
  docs/gettingstarted/autoupdate.md
Labels: 1.14, Needs Rebase, Out of Date Information

#256 Added a legacy category, addresses #254 and #216
  docs/legacy/index.md
  docs/legacy/porting1214.md
  mkdocs.yml
Labels: 1.14, New Page, Waiting for Changes

#260 Updated Environment Setup instructions for IntelliJ
  docs/forgedev/index.md
Labels: 1.14, Minor Text Fixes, Out of Date Information, Waiting for Changes
