Repository MinecraftForge/Documentation, pull requests merged in 2020-01, with the labels that each got.

#251 Delete old information about `TileEntityRendererFast`
  docs/tileentities/tesr.md
Labels: 1.15, Out of Date Information

#239 Updated Getting Started section
  docs/gettingstarted/autoupdate.md
  docs/gettingstarted/index.md
  docs/gettingstarted/structuring.md
Labels: 1.14, Out of Date Information, Waiting for Changes

#244 Updated Blocks section
  docs/blocks/blocks.md
  docs/blocks/interaction.md
  docs/blocks/states.md
Labels: 1.14, Out of Date Information, Waiting for Changes

#243 Update Rendering section
  docs/rendering/ister.md
  docs/rendering/teisr.md
  mkdocs.yml
Labels: 1.14, Out of Date Information, Waiting for Changes

#255 Change assets to data. Add note about common vanilla format for filename
  docs/utilities/recipes.md
Labels: 1.14, Out of Date Information, Waiting for Changes

#242 Updated Events section
  docs/events/intro.md
Labels: 1.14, Out of Date Information, Waiting for Changes

#240 Add explaination about side-only mods and network version predicates
  docs/concepts/sides.md
  docs/networking/simpleimpl.md
Labels: 1.14, Page Improvement, Waiting for Changes

#252 Update Item to use Item.Properties
  docs/items/items.md
Labels: 1.14, Needs Rebase, Out of Date Information

#249 Registries: Small fixes + add info about DeferredRegister
  docs/concepts/registries.md
Labels: 1.14, Needs Rebase, Out of Date Information
