Repository MinecraftForge/Documentation, pull requests merged in 2021-03, with the labels that each got.

#340 Updated Item property override in 1.16
  docs/models/overrides.md
Labels: 1.16, Minor Text Fixes, Page Improvement

#325 1.14.x -> 1.15.x Update
  docs/animation/implementing.md
  docs/blocks/blocks.md
  docs/blocks/interaction.md
  docs/blocks/states.md
  docs/conventions/loadstages.md
  docs/datastorage/capabilities.md
  docs/datastorage/worldsaveddata.md
  docs/effects/sounds.md
  docs/events/intro.md
  docs/models/advanced/ibakedmodel.md
  docs/models/advanced/itemoverridelist.md
  docs/models/advanced/perspective.md
  docs/models/blockstates/introduction.md
  docs/models/color.md
  docs/models/files.md
  docs/models/overrides.md
  docs/tileentities/tesr.md
  docs/tileentities/tileentity.md
  mkdocs.yml
Labels: 1.15, Minor Text Fixes, Page Improvement

#349 Distinguish MDK from source distribution
  docs/gettingstarted/index.md
Labels: 1.15, Minor Text Fixes, Page Improvement, Waiting for Changes
