Repository MinecraftForge/Documentation, pull requests merged in 2021-08, with the labels that each got.

#382 Add mention of RetroGradle to the legacy index page
  docs/legacy/index.md
Labels: Page Improvement, 1.16

#381 Fix version warning note from RtD
  forge_theme/css/version_warning_fix.css
  mkdocs.yml
Labels: Theme, 1.16

#375 Fix git clone command in Forgedev setup
  docs/forgedev/index.md
Labels: Minor Text Fixes, 1.16
