Repository MinecraftForge/Documentation, pull requests merged in 2021-01, with the labels that each got.

#327 Move and update the docs on lifecycle events
  docs/concepts/lifecycle.md
  docs/conventions/loadstages.md
  mkdocs.yml
Labels: 1.15, Page Improvement

#331 Supersedes #298, Updated TextComponentTranslation to TranslationTextComponent
  docs/concepts/internationalization.md
Labels: 1.15, Minor Text Fixes, Page Improvement

#352 Broken link fixes
  docs/gettingstarted/structuring.md
  docs/items/globallootmodifiers.md
  docs/models/advanced/ibakedmodel.md
  docs/models/blockstates/introduction.md
  docs/utilities/recipes.md
  docs/utilities/tags.md
Labels: 1.15, Minor Text Fixes, Page Improvement

#324 1.16.x Updates
  docs/blocks/blocks.md
  docs/blocks/states.md
  docs/gettingstarted/structuring.md
  docs/legacy/index.md
  docs/models/advanced/itemoverridelist.md
  docs/models/blockstates/introduction.md
  docs/models/color.md
  docs/models/overrides.md
  docs/rendering/ister.md
  docs/tileentities/tileentity.md
Labels: 1.16, Out of Date Information
