Repository MinecraftForge/Documentation, pull requests merged in 2022-02, with the labels that each got.

#402 [1.18] Improve BlockEntityType explanation
  docs/blockentities/blockentity.md
Labels: Page Improvement, 1.18

#403 [1.18] Upstream Registries Documentation
  docs/concepts/registries.md
Labels: Page Improvement, 1.18

#404 [1.18] Particle Overhaul
  docs/effects/particles.md
Labels: Out of Date Information, Page Improvement, 1.18

#401 Change optional array from deprecated to removed
  docs/utilities/tags.md
Labels: Out of Date Information, 1.18

#400 Change WorldSavedData to SavedData for 1.18.x
  docs/datastorage/saveddata.md
Labels: Out of Date Information, Minor Text Fixes, 1.18

#393 [1.16] Particle Overhaul
  docs/effects/particles.md
Labels: Out of Date Information, Page Improvement, 1.16

#392 [1.16] Improve TileEntityType Explanation
  docs/tileentities/tileentity.md
Labels: Page Improvement, 1.16

#405 [1.18] Clarify BlockState Definition
  docs/blocks/states.md
Labels: Page Improvement, Minor Text Fixes, 1.18

#397 Fix BlockState definition (#396)
  docs/blocks/states.md
Labels: Page Improvement, Minor Text Fixes, 1.16

#406 [1.18] Improve DistExecutor explanation
  docs/concepts/sides.md
Labels: Page Improvement, 1.18

#407 [1.16] Improve DistExecutor explanation
  docs/concepts/sides.md
Labels: Page Improvement, 1.16

#408 [1.16] Mention AdvancementProvider as usable
  docs/datagen/intro.md
Labels: Out of Date Information, Minor Text Fixes, 1.16

#409 Add info for registering to vanilla registries
  docs/concepts/registries.md
Labels: Page Improvement, 1.18
