Repository MinecraftForge/Documentation, pull requests merged in 2022-05, with the labels that each got.

#435 [1.18.x] A for Advancements
  docs/datagen/index.md
  docs/datagen/server/advancements.md
  docs/resources/server/advancements.md
  docs/resources/server/recipes/index.md
  mkdocs.yml
Labels: New Page, 1.18

#442 [1.18.x] Model Providers: The Long
  docs/datagen/client/modelproviders.md
  docs/datagen/index.md
Labels: New Page, 1.18

#447 [1.18.x] Fix typo in registries.md
  docs/concepts/registries.md
Labels: Typo, 1.18

#448 [1.16.x] Fix typo in registries.md
  docs/concepts/registries.md
Labels: Typo, 1.16

#445 [1.18.x] Probably a Loot Table Data Provider
  docs/datagen/index.md
  docs/datagen/server/loottables.md
  docs/resources/server/loottables.md
  mkdocs.yml
Labels: New Page, Page Improvement, 1.18
