Repository MinecraftForge/Documentation, pull requests merged in 2022-06, with the labels that each got.

#449 [1.18.x] Migrate Dropdown to 1.19
  mkdocs.yml
Labels: Out of Date Information, 1.18

#450 [1.19.x] Update Dropdown to Reflect 1.19 Changes
  mkdocs.yml
Labels: Out of Date Information, 1.19

#451 [1.19.x] The 1.19 Update
  docs/blocks/index.md
  docs/blocks/states.md
  docs/concepts/events.md
  docs/concepts/internationalization.md
  docs/concepts/lifecycle.md
  docs/concepts/registries.md
  docs/concepts/sides.md
  docs/datagen/client/modelproviders.md
  docs/datagen/server/advancements.md
  docs/datagen/server/loottables.md
  docs/datagen/server/tags.md
  docs/gameeffects/sounds.md
  docs/gettingstarted/index.md
  docs/gettingstarted/structuring.md
  docs/items/index.md
  docs/legacy/index.md
  docs/legacy/porting.md
  docs/misc/updatechecker.md
  docs/resources/server/glm.md
  docs/resources/server/recipes/custom.md
  docs/resources/server/recipes/incode.md
  docs/resources/server/tags.md
Labels: Out of Date Information, 1.19

#453 1.19: Add "settings.gradle" to required files in "Getting Started" step 3
  docs/gettingstarted/index.md
Labels: Minor Text Fixes, 1.19
