Repository MinecraftForge/Documentation, pull requests merged in 2023-05, with the labels that each got.

#490 [1.19.x] Rewrite Getting Started
  docs/concepts/resources.md
  docs/concepts/sides.md
  docs/contributing.md
  docs/datagen/client/modelproviders.md
  docs/gettingstarted/index.md
  docs/gettingstarted/modfiles.md
  docs/gettingstarted/structuring.md
  docs/gettingstarted/versioning.md
  docs/index.md
  docs/misc/updatechecker.md
  docs/resources/client/models/itemproperties.md
  mkdocs.yml
Labels: Page Improvement, 1.19

#493 [1.19.x] Document Forge extensions of the model JSON format
  docs/rendering/modelextensions/ambientocclusion_annotated.png
  docs/rendering/modelextensions/facedata.md
  docs/rendering/modelextensions/rendertypes.md
  docs/rendering/modelextensions/transforms.md
  docs/rendering/modelextensions/visibility.md
  docs/rendering/modelloaders/index.md
  mkdocs.yml
Labels: New Page, Page Improvement, 1.19

#497 [ForgeGradle] The ForgeGradle 6 Update
  docs/configuration/advanced.md
  docs/configuration/index.md
  docs/configuration/runs.md
  docs/contributing.md
  docs/dependencies/index.md
  docs/dependencies/jarinjar.md
  docs/gettingstarted/index.md
  docs/index.md
  docs/porting.md
  mkdocs.yml
Labels: Out of Date Information, Page Improvement, FG6
